version: '3'
services:
  nginx:
    image: nginx:latest                 # 镜像`nginx:1.27.0`
    container_name: nginx               # 容器名为'nginx'
    restart: unless-stopped             # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:  
      - ./conf/nginx.conf:/etc/nginx/nginx.conf  # 挂载配置文件  
      - ./html:/usr/share/nginx/html               # 挂载 HTML 文件  
      - ./log:/var/log/nginx
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:                              # 映射端口
      - "80:80"