version: '3.7'

services:
  zerotier-moon:
    image: zerotier/zerotier:latest
    container_name: zerotier-moon
    restart: always
    ports:
      - "9993:9993/udp"  # ZeroTier 使用的 UDP 端口
    volumes:
      - ./data:/var/lib/zerotier-one  # 持久化 Moon 数据
    environment:
      - ZT_NETWORK_ID=e5cd7a9e1ca85d32
      - ZT_MOON=true  # 启用 Moon 模式
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    privileged: true
