version: "3.3"
services:
   redis:
    image: redis:6.2.7
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - redis:/redis
      # # 数据文件
      # - /docker/redis/data/:/redis/data/
    command: redis-server --notify-keyspace-events KEA
    privileged: true
volumes:
  redis:

  
